{{- if $.Values.knative.enabled }}
{{- if $.Values.istio.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-serving-system-namespace
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          knative.openshift.io/system-namespace: 'true'
  podSelector: {}
  policyTypes:
  - Ingress
{{- end }}
{{- end }}
