{{- range $key, $val := $.Values.global.apps }}
{{- if contains $key "quarkus"}}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: quarkus
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: quay.io/quarkus/ubi-quarkus-native-s2i:20.2.0-java11
    generation: 1
    importPolicy: {}
    name: 20.2.0-java11
    referencePolicy:
      type: Source
{{- else }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: {{ $key }}
  name: {{ $key }}
spec:
  lookupPolicy:
    local: false
{{- end }}
{{- end }}