{{- range $key, $val := $.Values.global.apps }}
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: triggerbinding-{{ $key }}-build
spec:
  params:
    - name: git-url
      value: $(body.repository.url)
    - name: git-branch
      value: $(body.ref)
    - name: git-commit
      value: $(body.head_commit.id)
    - name: git-commit-message
      value: $(body.head_commit.message)
    - name: content-type
      value: $(header.Content-Type)
    - name: pusher-name
      value: $(body.pusher.name)
{{- end }}