{{- range $key, $val := $.Values.global.apps }}
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: triggertemplate-{{ $key }}-build
spec:
  params:
    - name: git-url
    - name: git-branch
    - name: git-commit
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: run-{{ $key }}-$(uid)
      spec:
        serviceAccountName: {{ $.Values.sa }}
        pipelineRef:
          name: pipeline-{{ $key }}-build
        params:
          - name: app-git-url  
            value: $(tt.params.git-url)
          - name: git-branch  
            value: $(tt.params.git-branch)
          - name: git-commit  
            value: $(tt.params.git-commit)
          - name: functTestRepoBranch
            value: {{ $.Values.functTestRepoBranch }}
          - name: functTestRepo
            value: {{ $.Values.functTestRepo }}
        workspaces:
          - name: app-source
            persistentVolumeClaim:
              claimName: pipeline-{{ $key }}-build-workspace-pvc
                
{{- end }}
